version: "3.3"
services:

  nginx:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    ports:
      - "88:80"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    links:
      - php:php
    restart: "no"

  php:
    build: docker/php
    expose:
      - "9000"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    links:
      - mysql
      - redis
    volumes:
      - ./:/var/www/html
    restart: "no"

  mysql:
    image: mysql:8.0.32
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "7306:3306"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    volumes:
      - ./docker/mysql/my.cnf:/etc/my.cnf
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    restart: "no"

  redis:
    image: redis
    ports:
      - "7379:6379"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    volumes:
      - ./data/redis:/data
    command: redis-server --appendonly yes
    restart: "no"

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    environment:
      - PMA_ARBITRARY=1
    restart: "no"


